base_url = "https://aaronkyriesenbach.com"
title = "Aaron Ky-Riesenbach"
description = "Aaron Ky-Riesenbach"
default_language = "en"

compile_sass = false
build_search_index = false
generate_feeds = false

taxonomies = [{ name = "tags", feed = false }]

[markdown]
smart_punctuation = true

[markdown.highlighting]
theme = "dracula"

[extra]
blog_enabled = false
projects_enabled = false

menu = [
  { name = "Home", url = "/" },
  { name = "Work", url = "/work/" },
  { name = "Music", url = "/music/" },
  { name = "Resume", url = "/resume/" },
]

socials = [
  { name = "GitHub", url = "https://github.com/", icon = "github" },
  { name = "LinkedIn", url = "https://www.linkedin.com/", icon = "linkedin" },
  { name = "Email", url = "mailto:hello@aaronkyriesenbach.com", icon = "email" },
]
