name: Deploy

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: aaronkyriesenbach/workflows/.github/workflows/zola-pages.yaml@master
    with:
      zola-version: "0.23.4"
    permissions:
      contents: read
      pages: write
      id-token: write
